/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradleproject1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Default
 */
public class Proyecto_Final extends javax.swing.JFrame {
    String archivoSalida = "C:\\ProyectoFinal\\Agenda.txt";
    String rutaArchivo = "C:\\ProyectoFinal";
    DefaultListModel dfListModel;
    ArrayList<Agenda> listaContactos = new ArrayList<Agenda>();
    int maxId = 0;
    JTextField texto1,texto2;
    JButton boton1, boton2;
    JPanel contentpane;
    /**
     * Creates new form Proyecto_Final
     */
    public Proyecto_Final(){
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        txtNombre = new java.awt.TextField();
        txtApellidos = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        txtTelefono = new java.awt.TextField();
        label4 = new java.awt.Label();
        txtCorreo = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstContactos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnEliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENDA DE CONTACTOS");
        setResizable(false);

        label1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label1.setName("lblNombre"); // NOI18N
        label1.setText("Nombre(s):");

        txtNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N

        txtApellidos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtApellidos.setName("txtApellidos"); // NOI18N

        label2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label2.setName("lblNombre"); // NOI18N
        label2.setText("Apellido(s):");

        label3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label3.setName("lblTelefono"); // NOI18N
        label3.setText("Teléfono:");

        txtTelefono.setColumns(1);
        txtTelefono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTelefono.setMaximumSize(new java.awt.Dimension(10, 10));
        txtTelefono.setName("txtTelefono"); // NOI18N
        txtTelefono.setPreferredSize(new java.awt.Dimension(10, 10));

        label4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label4.setName("lblCorreo"); // NOI18N
        label4.setText("Correo Electrónico:");

        txtCorreo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCorreo.setName("txtCorreo"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lstContactos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lstContactos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstContactos.setToolTipText("Información de los contactos...");
        lstContactos.setComponentPopupMenu(jPopupMenu1);
        lstContactos.setName("lstContactos"); // NOI18N
        lstContactos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstContactosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstContactos);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAgregar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setName("btnAgregar"); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setName("btnSalir"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnEliminar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setName("btnEliminar"); // NOI18N
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatosTxt(){
        String linea = "";
        String dfModel = "";
        dfListModel = new DefaultListModel();

        try{
            FileReader archivoDatos = new FileReader(archivoSalida);
            BufferedReader buffer = new BufferedReader(archivoDatos);
            while ((linea = buffer.readLine()) != null) {
                String[] datosContacto = linea.split(",");
                if (linea.trim().length() > 0 && datosContacto.length > 0){
                    Agenda a = new Agenda();
                    dfModel = datosContacto[0] + "," + datosContacto[2] + "," + datosContacto[1];
                    a.setId(datosContacto[0]); a.setNombre(datosContacto[1]);   a.setApellidos(datosContacto[2]);
                                               a.setTelefono(datosContacto[3]); a.setCorreo(datosContacto[4].toLowerCase());
                    listaContactos.add(a);
                    dfListModel.addElement(dfModel);
                }
            }
            lstContactos.setModel(dfListModel);
            buffer.close();
            archivoDatos.close();
        } catch(IOException e){
            e.printStackTrace();
        }
    }
    
    private void guardarContactos(){
        int id = 1;
        try{
            if (listaContactos.size() >= 0){
                File archivo = new File(archivoSalida);
                archivo.delete();
                FileWriter archSalida = new FileWriter(archivoSalida, true);
                BufferedWriter bufSalida = new BufferedWriter(archSalida);
                for(Agenda agenda: listaContactos){
                    bufSalida.write(String.valueOf(id) + "," + agenda.getNombre() + "," + agenda.getApellidos() + "," + agenda.getTelefono() + "," + agenda.getCorreo() + "\n");
                    id += 1;
                }
                bufSalida.close(); archSalida.close();
                inicializar();
                JOptionPane.showMessageDialog(null, "INFORMACIÓN ACTUALIZADA EXITOSAMENTE!");     
            }
            else
                JOptionPane.showMessageDialog(null, "IMPOSIBLE GUARDAR...\n\nLA LISTA DE CONTACTOS ESTA VACÍA!");                                    
        } catch(IOException e){
            e.printStackTrace();
        }
    }
    
    private void inicializar(){
        File directorio = new File(rutaArchivo);
        if (!directorio.exists()) 
            if (directorio.mkdirs()) 
                System.out.println("Directorio creado");
            else 
                System.out.println("Error al crear directorio");
        txtNombre.setText(""); txtApellidos.setText(""); txtTelefono.setText(""); txtCorreo.setText("");
        listaContactos.clear();  cargarDatosTxt();
    }
    
    private boolean controlContactos(boolean llenarControles, boolean eliminarContacto, boolean guardaContacto){
        int index = lstContactos.getSelectedIndex();
        String elementoSel = lstContactos.getSelectedValue();
        if (llenarControles){
            String[] contacto = lstContactos.getSelectedValue().split(",");
            for(Agenda agenda: listaContactos)
                if (agenda.getNombre().contains(contacto[2]) &&  agenda.getApellidos().contains(contacto[1])){
                    txtNombre.setText(agenda.getNombre()); txtApellidos.setText(agenda.getApellidos());
                    txtTelefono.setText(agenda.getTelefono()); txtCorreo.setText(agenda.getCorreo().toLowerCase());
                }
        } else if(eliminarContacto){
            if (index != -1){
                String[] contacto = lstContactos.getSelectedValue().split(",");
                for(Agenda contact: listaContactos){
                    if (contact.getNombre().trim().contains(contacto[2].trim()) && contact.getApellidos().trim().contains(contacto[1].trim())){
                        listaContactos.remove(index);
                        guardarContactos();
                        return true;
                    }
                }
            }
        } else if (guardaContacto) {
            String nombre = txtNombre.getText().trim().toUpperCase();
            String apellidos = txtApellidos.getText().trim().toUpperCase();
            String telefono = txtTelefono.getText().trim().toUpperCase();
            String correo = txtCorreo.getText().trim().toLowerCase();
            if (validarControles()){
                if (index == -1){
                    Agenda a = new Agenda();
                    a.setId("*"); a.setNombre(nombre);     a.setApellidos(apellidos);
                                  a.setTelefono(telefono); a.setCorreo(correo);
                    listaContactos.add(a);
                } else {
                    String[] contacto = elementoSel.split(",");
                    for(Agenda contact: listaContactos){
                        if(Integer.parseInt(contact.getId()) == Integer.parseInt(contacto[0])){
                            contact.setNombre(nombre);     contact.setApellidos(apellidos);
                            contact.setTelefono(telefono); contact.setCorreo(correo);
                        }            
                    }
                }
                guardarContactos();
            }
        }
        //lstContactos.clearSelection();
        return true;
    }            
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        inicializar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        controlContactos(false, false, true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private boolean validarControles(){
        String emailFormato ="@.";  
        String telformato = "1234567890";

        if (txtNombre.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "INGRESE UN  [NOMBRE]  DE CONTACTO.");
            txtNombre.requestFocusInWindow();
            return false;
        } else if (txtApellidos.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "INGRESE LOS  [APELLIDOS]  DEL CONTACTO.");
            txtApellidos.requestFocusInWindow();
            return false;
        } else if (txtTelefono.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "INGRESE UN  [TELEFONO]  VÁLIDO DEL CONTACTO.");
            txtTelefono.requestFocusInWindow();
            return false;
        } else if (txtTelefono.getText().trim().length() > 10){
            JOptionPane.showMessageDialog(null, "LA LONGITUD DEL NÚMERO DE  [TELEFONO]  DEBE SER 10 DÍGITOS.");
            txtTelefono.requestFocusInWindow();
            return false;
        } else if (txtCorreo.getText().trim().length() == 0 || txtCorreo.getText().trim().contains(" ") || 
                  !txtCorreo.getText().trim().contains("@") || !txtCorreo.getText().trim().contains(".")){
            JOptionPane.showMessageDialog(null, "INGRESE UN   [CORREO]  VALIDO DEL CONTACTO.");
            txtCorreo.requestFocusInWindow();
            return false;
        }
        return true;
    }
    
    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "DESEAS ELIMINAR EL CONTACTO SELECCIONADO?", "SELECCIONA...", JOptionPane.YES_NO_OPTION);
        if (opcion == 0)
            controlContactos(false, true, false);
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void lstContactosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstContactosValueChanged
        // TODO add your handling code here:
        int index = lstContactos.getSelectedIndex();
        if (index != -1)
           controlContactos(true, false, false);
    }//GEN-LAST:event_lstContactosValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto_Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JList<String> lstContactos;
    private java.awt.TextField txtApellidos;
    private java.awt.TextField txtCorreo;
    private java.awt.TextField txtNombre;
    private java.awt.TextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}

class Agenda {
    public String id, nombre, apellidos, telefono, correo;

    public Agenda() {
    }

    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }
    
    public void setNombre(String nombre){
        this.nombre = nombre;
    }
    
    public String getApellidos() {
        return apellidos;
    }
    
    public void setApellidos(String apellidos){
        this.apellidos = apellidos;
    }
    
    public String getTelefono() {
        return telefono;
    }
    
    public void setTelefono(String telefono){
        this.telefono = telefono;
    }
    
    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo){
        this.correo = correo;
    }
}